### ISSUE TITLE
SQL Treesitter module not working on mac

### ISSUE THREAD

**Issue by snakethatlovesstaticlibs** [mishazharov/emacs#3]
```
⛔ Warning (treesit): Error encountered when installing language grammar: (treesit-error Command: cc -fPIC -c -I. parser.c Error output: clang: error: no such file or directory: 'parser.c'
clang: error: no input files
)
⛔ Warning (treesit): The installed language grammar for sql cannot be located or has problems (not-found): (libtree-sitter-sql.so libtree-sitter-sql.dylib) No such file or directory
```

**Comment by mishazharov** [comment]
Doesn't work on ubuntu either, looks like https://github.com/m-novikov/tree-sitter-sql changed since the last time I ran `treesit-install-language-grammar` to be somehow incompatible

**Comment by mishazharov** [comment]
I filed https://debbugs.gnu.org/cgi/bugreport.cgi?bug=61849 in Emacs, and it seems that this is working as intended. As a workaround I'll switch to https://github.com/DerekStride/tree-sitter-sql and if this issue comes up again I will write up a custom installer to mimic `treesit-install-language-grammar` (maybe just put some advice around it as well)

**Comment by mishazharov** [comment]
The emacs maintainers filed a ticket in the tree-sitter-sql repo: https://github.com/m-novikov/tree-sitter-sql/issues/72

**Comment by mishazharov** [comment]
This might also affect the current treesitter grammar I'm using: https://github.com/DerekStride/tree-sitter-sql/issues/120
